highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: :title.html
paginate: 5
plugins: [jekyll-paginate]
port: 4000
safe: true
url: http://jekyller.github.io/vitae
author: Jaswant Pakki

# edit this section with your information
# jekyller.github.io - all contents run on /vitae/
# for a normal use at the base of the server change it to "/"
baseurl: /vitae/
title: Jaswant Pakki's Resume
name: Jaswant Pakki
email: jpakki1@asu.edu
email_full: mailto:jpakki1@asu.edu
website: www.jaswantpakki.com
website_full: https://www.jaswantpakki.com
github: jpakki
twitter: jaswantpakki
#google_analytics: UA-69300817-1

# needed for travis-ci build
exclude: [vendor]
